# Generated by Django 5.1.7 on 2025-04-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_settings_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
