# Generated by Django 5.1.6 on 2025-02-20 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task', 'Task'), ('exam', 'Exam'), ('poll', 'Poll')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('student', 'Student')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'poll'}, on_delete=django.db.models.deletion.CASCADE, to='school.activity')),
                ('student', models.ForeignKey(limit_choices_to={'group': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='school.profile')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.ManyToManyField(limit_choices_to={'group': 'student'}, to='school.profile'),
        ),
        migrations.CreateModel(
            name='Theclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('professor', models.ForeignKey(limit_choices_to={'group': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to='school.profile')),
                ('students', models.ManyToManyField(limit_choices_to={'group': 'student'}, related_name='classes', to='school.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'group': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='school.profile')),
                ('theclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.theclass')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.theclass'),
        ),
    ]
