# Generated by Django 5.1.6 on 2025-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('task', 'Tareas'), ('exam', 'Examen'), ('poll', 'Votacion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Profesor'), ('student', 'Alumno')], max_length=10),
        ),
    ]
