# Generated by Django 5.1.6 on 2025-02-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_activity_activity_type_alter_profile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresult',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='theclass',
        ),
        migrations.RemoveField(
            model_name='pollresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theclass',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='theclass',
            name='students',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='PollResult',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Theclass',
        ),
    ]
