# Generated by Django 5.1.6 on 2025-03-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group',
            new_name='group_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rol',
        ),
    ]
