# Generated by Django 5.1.6 on 2025-03-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_group_userprofile_group_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group_class',
            new_name='insignia',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='professional_title',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
