# Generated by Django 5.1.6 on 2025-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_group_class_userprofile_insignia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='num_list',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
