# Generated by Django 5.1.7 on 2025-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_userprofile_team_alter_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
