# Generated by Django 5.1.7 on 2025-04-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_userprofile_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
